name: ci

on:
  push:
    branches:
      - 'main'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: DockerHub build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: andrewm4894/netdata-ml-app:latest
  heroku:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Heroku Login
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login
      - name: Heroku config
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku config:set NETDATAMLAPP_HOSTS=london.my-netdata.io,newyork.my-netdata.io
      - name: Heroku Build and push
        env:
          PORT: 29999
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:push -a netdata-ml-app web
      - name: Heroku release
        env:
          PORT: 29999
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          NETDATAMLAPP_HOSTS: "london.my-netdata.io,newyork.my-netdata.io"
        run: heroku container:release -a netdata-ml-app web